import { BlogArticle } from "@/types/blog";

export const blogArticles: BlogArticle[] = [
  {
    id: 1,
    title: "Ngành Marketing là gì? Cơ hội việc làm mới nhất 2026",
    excerpt: "Marketing là một trong những ngành đóng vai trò quan trọng trong hầu hết các doanh nghiệp hiện đại. Tìm hiểu về cơ hội nghề nghiệp và mức lương hấp dẫn trong ngành.",
    image: "/landing/slide1.png",
    category: "Định hướng nghề nghiệp",
    date: "10/01/2026",
    readTime: "5 phút đọc",
  },
  {
    id: 2,
    title: "Tài mẫu sơ yếu lý lịch xin việc chuẩn nhất 2026",
    excerpt: "Sơ yếu lý lịch là một trong những giấy tờ quan trọng nhất khi chuẩn bị hồ sơ xin việc.",
    image: "/landing/slide2.png",
    category: "Bí kíp tìm việc",
    date: "08/01/2026",
    readTime: "8 phút đọc",
  },
  {
    id: 3,
    title: "Top 10 kỹ năng mềm cần thiết cho Freelancer",
    excerpt: "Ngoài chuyên môn, freelancer cần trang bị những kỹ năng mềm quan trọng.",
    image: "/landing/slide3.png",
    category: "Hành trang nghề nghiệp",
    date: "05/01/2026",
    readTime: "6 phút đọc",
  },
  {
    id: 4,
    title: "Cách đàm phán lương hiệu quả khi phỏng vấn",
    excerpt: "Học cách đàm phán lương một cách tự tin và chuyên nghiệp.",
    image: "/landing/slide4.png",
    category: "Chế độ lương thưởng",
    date: "03/01/2026",
    readTime: "7 phút đọc",
  },
  {
    id: 5,
    title: "Xu hướng tuyển dụng IT năm 2026",
    excerpt: "Những vị trí IT hot nhất, mức lương và kỹ năng được săn đón.",
    image: "/landing/slide1.png",
    category: "Thị trường & xu hướng",
    date: "01/01/2026",
    readTime: "10 phút đọc",
  },
  {
    id: 6,
    title: "Làm việc remote hiệu quả: Bí quyết từ chuyên gia",
    excerpt: "Những mẹo giúp bạn làm việc từ xa hiệu quả.",
    image: "/landing/slide2.png",
    category: "Hành trang nghề nghiệp",
    date: "28/12/2025",
    readTime: "5 phút đọc",
  },
  {
    id: 7,
    title: "Phỏng vấn online: Chuẩn bị như thế nào?",
    excerpt: "Hướng dẫn chi tiết cách chuẩn bị cho buổi phỏng vấn trực tuyến.",
    image: "/landing/slide3.png",
    category: "Bí kíp tìm việc",
    date: "25/12/2025",
    readTime: "6 phút đọc",
  },
  {
    id: 8,
    title: "Ngành Data Science: Lộ trình học",
    excerpt: "Tất cả những gì bạn cần biết về ngành Data Science.",
    image: "/landing/slide4.png",
    category: "Kiến thức chuyên ngành",
    date: "22/12/2025",
    readTime: "12 phút đọc",
  },
  {
    id: 9,
    title: "Cách xây dựng portfolio ấn tượng",
    excerpt: "Portfolio là vũ khí quan trọng nhất của designer.",
    image: "/landing/slide1.png",
    category: "Hành trang nghề nghiệp",
    date: "20/12/2025",
    readTime: "8 phút đọc",
  },
  {
    id: 10,
    title: "Kỹ năng giao tiếp trong công việc",
    excerpt: "Giao tiếp hiệu quả giúp bạn thăng tiến nhanh hơn.",
    image: "/landing/slide2.png",
    category: "Kỹ năng mềm",
    date: "18/12/2025",
    readTime: "5 phút đọc",
  },
  {
    id: 11,
    title: "Quản lý thời gian hiệu quả",
    excerpt: "Bí quyết quản lý thời gian cho người bận rộn.",
    image: "/landing/slide3.png",
    category: "Hành trang nghề nghiệp",
    date: "15/12/2025",
    readTime: "7 phút đọc",
  },
  {
    id: 12,
    title: "Networking: Xây dựng mối quan hệ",
    excerpt: "Cách mở rộng mạng lưới quan hệ trong công việc.",
    image: "/landing/slide4.png",
    category: "Kỹ năng mềm",
    date: "12/12/2025",
    readTime: "6 phút đọc",
  },
  {
    id: 13,
    title: "Chuyển ngành thành công ở tuổi 30",
    excerpt: "Kinh nghiệm chuyển ngành cho người đã có kinh nghiệm.",
    image: "/landing/slide1.png",
    category: "Định hướng nghề nghiệp",
    date: "10/12/2025",
    readTime: "9 phút đọc",
  },
  {
    id: 14,
    title: "Freelancer vs Full-time: Nên chọn gì?",
    excerpt: "So sánh ưu nhược điểm của hai hình thức làm việc.",
    image: "/landing/slide2.png",
    category: "Định hướng nghề nghiệp",
    date: "08/12/2025",
    readTime: "8 phút đọc",
  },
];
